name: qrcodescan
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  google_fonts: ^5.1.0
  qr_code_scanner: ^1.0.1
  http: ^1.1.0
  bottom_bar: ^2.0.3
  flutter_svg: 2.0.7
  shared_preferences: ^2.2.1
  intl: ^0.17.0
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  flutter: 
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/applogo.png"

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

